### ISSUE TITLE
Add todo for contributors

### ISSUE THREAD

**Issue by kevin-schmitt** [diegomais/node-js-design-patterns#15]
Hello,

I want help to improve this project :)
But i have not idea what is next step in you todo (pattern, refactor ...) it's possible to add document explain it please?
You can assign me a task for help you maybe?

Thanks

**Comment by diegomais** [comment]
Hello @kevin-schmitt ,

Sorry for the delay, please check the [How to contribute guide](https://github.com/diegomais/node-js-design-patterns/blob/master/CONTRIBUTING.md).
